# Generated by Django 6.0.2 on 2026-03-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='trainmodel',
            name='version',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='trainmodel',
            name='tags',
            field=models.ManyToManyField(to='core.tag'),
        ),
    ]
