# Generated by Django 6.0.4 on 2026-04-15 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_trainmodel_architecture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trainmodel",
            options={"ordering": ["id"]},
        ),
    ]
